---
title: "Loading and preprocessing"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Loading and preprocessing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, setup=TRUE}
library(navr)
library(ggplot2)
obj <- navr_object
```

## Preprocessing
We can add desired columns one by one
```{r}
colnames(obj$data)
obj <- add_time_columns(obj)
colnames(obj$data)
obj <- add_distances(obj)
colnames(obj$data)
obj <- add_speeds(obj)
colnames(obj$data)
```

Or we can use a shorthand and add all of them together
```{r}
obj <- navr_object
obj <- add_columns_navr(obj)
colnames(obj$data)
```

## Removing too large speeds/teleports
```{r}
#this function picks unreal speeds
i_speeds <- pick_unreal_speeds(obj, 3, "std")

#this function removes given speed AND distance measurements and recalculates total distance
obj <- remove_unreal_speeds(obj, indices = i_speeds, total_recalculate = T)
```
